export const Cities = [
  { id: 1, value: "CUENCA" },
  { id: 2, value: "GIRÓN" },
  { id: 3, value: "GUALACEO" },
  { id: 4, value: "NABÓN" },
  { id: 5, value: "PAUTE" },
  { id: 6, value: "PUCARA" },
  { id: 7, value: "SAN FERNANDO" },
  { id: 8, value: "SANTA ISABEL" },
  { id: 9, value: "SIGSIG" },
  { id: 10, value: "OÑA" },
  { id: 11, value: "CHORDELEG" },
  { id: 12, value: "EL PAN" },
  { id: 13, value: "SEVILLA DE ORO" },
  { id: 14, value: "GUACHAPALA" },
  { id: 15, value: "CAMILO PONCE ENRÍQUEZ" },
  { id: 16, value: "GUARANDA" },
  { id: 17, value: "CHILLANES" },
  { id: 18, value: "CHIMBO" },
  { id: 19, value: "ECHEANDÍA" },
  { id: 20, value: "SAN MIGUEL" },
  { id: 21, value: "CALUMA" },
  { id: 22, value: "LAS NAVES" },
  { id: 23, value: "AZOGUES" },
  { id: 24, value: "BIBLIÁN" },
  { id: 25, value: "CAÑAR" },
  { id: 26, value: "LA TRONCAL" },
  { id: 27, value: "EL TAMBO" },
  { id: 28, value: "DÉLEG" },
  { id: 29, value: "SUSCAL" },
  { id: 30, value: "TULCÁN" },
  { id: 31, value: "BOLÍVAR" },
  { id: 32, value: "ESPEJO" },
  { id: 33, value: "MIRA" },
  { id: 34, value: "MONTÚFAR" },
  { id: 35, value: "SAN PEDRO DE HUACA" },
  { id: 36, value: "LATACUNGA" },
  { id: 37, value: "LA MANÁ" },
  { id: 38, value: "PANGUA" },
  { id: 39, value: "PUJILI" },
  { id: 40, value: "SALCEDO" },
  { id: 41, value: "SAQUISILÍ" },
  { id: 42, value: "SIGCHOS" },
  { id: 43, value: "RIOBAMBA" },
  { id: 44, value: "ALAUSI" },
  { id: 45, value: "COLTA" },
  { id: 46, value: "CHAMBO" },
  { id: 47, value: "CHUNCHI" },
  { id: 48, value: "GUAMOTE" },
  { id: 49, value: "GUANO" },
  { id: 50, value: "PALLATANGA" },
  { id: 51, value: "PENIPE" },
  { id: 52, value: "CUMANDÁ" },
  { id: 53, value: "MACHALA" },
  { id: 54, value: "ARENILLAS" },
  { id: 55, value: "ATAHUALPA" },
  { id: 56, value: "BALSAS" },
  { id: 57, value: "CHILLA" },
  { id: 58, value: "EL GUABO" },
  { id: 59, value: "HUAQUILLAS" },
  { id: 60, value: "MARCABELÍ" },
  { id: 61, value: "PASAJE" },
  { id: 62, value: "PIÑAS" },
  { id: 63, value: "PORTOVELO" },
  { id: 64, value: "SANTA ROSA" },
  { id: 65, value: "ZARUMA" },
  { id: 66, value: "LAS LAJAS" },
  { id: 67, value: "ESMERALDAS" },
  { id: 68, value: "ELOY ALFARO" },
  { id: 69, value: "MUISNE" },
  { id: 70, value: "QUININDÉ" },
  { id: 71, value: "SAN LORENZO" },
  { id: 72, value: "ATACAMES" },
  { id: 73, value: "RIOVERDE" },
  { id: 74, value: "LA CONCORDIA" },
  { id: 75, value: "GUAYAQUIL" },
  { id: 76, value: "ALFREDO BAQUERIZO MORENO (JUJÁN)" },
  { id: 77, value: "BALAO" },
  { id: 78, value: "BALZAR" },
  { id: 79, value: "COLIMES" },
  { id: 80, value: "DAULE" },
  { id: 81, value: "DURÁN" },
  { id: 82, value: "EL EMPALME" },
  { id: 83, value: "EL TRIUNFO" },
  { id: 84, value: "MILAGRO" },
  { id: 85, value: "NARANJAL" },
  { id: 86, value: "NARANJITO" },
  { id: 87, value: "PALESTINA" },
  { id: 88, value: "PEDRO CARBO" },
  { id: 89, value: "SAMBORONDÓN" },
  { id: 90, value: "SANTA LUCÍA" },
  { id: 91, value: "SALITRE (URBINA JADO)" },
  { id: 92, value: "SAN JACINTO DE YAGUACHI" },
  { id: 93, value: "PLAYAS" },
  { id: 94, value: "SIMÓN BOLÍVAR" },
  { id: 95, value: "CORONEL MARCELINO MARIDUEÑA" },
  { id: 96, value: "LOMAS DE SARGENTILLO" },
  { id: 97, value: "NOBOL" },
  { id: 98, value: "GENERAL ANTONIO ELIZALDE" },
  { id: 99, value: "ISIDRO AYORA" },
  { id: 100, value: "IBARRA" },
  { id: 101, value: "ANTONIO ANTE" },
  { id: 102, value: "COTACACHI" },
  { id: 103, value: "OTAVALO" },
  { id: 104, value: "PIMAMPIRO" },
  { id: 105, value: "SAN MIGUEL DE URCUQUÍ" },
  { id: 106, value: "LOJA" },
  { id: 107, value: "CALVAS" },
  { id: 108, value: "CATAMAYO" },
  { id: 109, value: "CELICA" },
  { id: 110, value: "CHAGUARPAMBA" },
  { id: 111, value: "ESPÍNDOLA" },
  { id: 112, value: "GONZANAMÁ" },
  { id: 113, value: "MACARÁ" },
  { id: 114, value: "PALTAS" },
  { id: 115, value: "PUYANGO" },
  { id: 116, value: "SARAGURO" },
  { id: 117, value: "SOZORANGA" },
  { id: 118, value: "ZAPOTILLO" },
  { id: 119, value: "PINDAL" },
  { id: 120, value: "QUILANGA" },
  { id: 121, value: "OLMEDO" },
  { id: 122, value: "BABAHOYO" },
  { id: 123, value: "BABA" },
  { id: 124, value: "MONTALVO" },
  { id: 125, value: "PUEBLOVIEJO" },
  { id: 126, value: "QUEVEDO" },
  { id: 127, value: "URDANETA" },
  { id: 128, value: "VENTANAS" },
  { id: 129, value: "VÍNCES" },
  { id: 130, value: "PALENQUE" },
  { id: 131, value: "BUENA FÉ" },
  { id: 132, value: "VALENCIA" },
  { id: 133, value: "MOCACHE" },
  { id: 134, value: "QUINSALOMA" },
  { id: 135, value: "PORTOVIEJO" },
  { id: 136, value: "BOLÍVAR" },
  { id: 137, value: "CHONE" },
  { id: 138, value: "EL CARMEN" },
  { id: 139, value: "FLAVIO ALFARO" },
  { id: 140, value: "JIPIJAPA" },
  { id: 141, value: "JUNÍN" },
  { id: 142, value: "MANTA" },
  { id: 143, value: "MONTECRISTI" },
  { id: 144, value: "PAJÁN" },
  { id: 145, value: "PICHINCHA" },
  { id: 146, value: "ROCAFUERTE" },
  { id: 147, value: "SANTA ANA" },
  { id: 148, value: "SUCRE" },
  { id: 149, value: "TOSAGUA" },
  { id: 150, value: "24 DE MAYO" },
  { id: 151, value: "PEDERNALES" },
  { id: 152, value: "OLMEDO" },
  { id: 153, value: "PUERTO LÓPEZ" },
  { id: 154, value: "JAMA" },
  { id: 155, value: "JARAMIJÓ" },
  { id: 156, value: "SAN VICENTE" },
  { id: 157, value: "MORONA" },
  { id: 158, value: "GUALAQUIZA" },
  { id: 159, value: "LIMÓN INDANZA" },
  { id: 160, value: "PALORA" },
  { id: 161, value: "SANTIAGO" },
  { id: 162, value: "SUCÚA" },
  { id: 163, value: "HUAMBOYA" },
  { id: 164, value: "SAN JUAN BOSCO" },
  { id: 165, value: "TAISHA" },
  { id: 166, value: "LOGROÑO" },
  { id: 167, value: "PABLO SEXTO" },
  { id: 168, value: "TIWINTZA" },
  { id: 169, value: "TENA" },
  { id: 170, value: "ARCHIDONA" },
  { id: 171, value: "EL CHACO" },
  { id: 172, value: "QUIJOS" },
  { id: 173, value: "CARLOS JULIO AROSEMENA TOLA" },
  { id: 174, value: "PASTAZA" },
  { id: 175, value: "MERA" },
  { id: 176, value: "SANTA CLARA" },
  { id: 177, value: "ARAJUNO" },
  { id: 178, value: "QUITO" },
  { id: 179, value: "CAYAMBE" },
  { id: 180, value: "MEJIA" },
  { id: 181, value: "PEDRO MONCAYO" },
  { id: 182, value: "RUMIÑAHUI" },
  { id: 183, value: "SAN MIGUEL DE LOS BANCOS" },
  { id: 184, value: "PEDRO VICENTE MALDONADO" },
  { id: 185, value: "PUERTO QUITO" },
  { id: 186, value: "AMBATO" },
  { id: 187, value: "BAÑOS DE AGUA SANTA" },
  { id: 188, value: "CEVALLOS" },
  { id: 189, value: "MOCHA" },
  { id: 190, value: "PATATE" },
  { id: 191, value: "QUERO" },
  { id: 192, value: "SAN PEDRO DE PELILEO" },
  { id: 193, value: "SANTIAGO DE PÍLLARO" },
  { id: 194, value: "TISALEO" },
  { id: 195, value: "ZAMORA" },
  { id: 196, value: "CHINCHIPE" },
  { id: 197, value: "NANGARITZA" },
  { id: 198, value: "YACUAMBI" },
  { id: 199, value: "YANTZAZA (YANZATZA)" },
  { id: 200, value: "EL PANGUI" },
  { id: 201, value: "CENTINELA DEL CÓNDOR" },
  { id: 202, value: "PALANDA" },
  { id: 203, value: "PAQUISHA" },
  { id: 204, value: "SAN CRISTÓBAL" },
  { id: 205, value: "ISABELA" },
  { id: 206, value: "SANTA CRUZ" },
  { id: 207, value: "LAGO AGRIO" },
  { id: 208, value: "GONZALO PIZARRO" },
  { id: 209, value: "PUTUMAYO" },
  { id: 210, value: "SHUSHUFINDI" },
  { id: 211, value: "SUCUMBÍOS" },
  { id: 212, value: "CASCALES" },
  { id: 213, value: "CUYABENO" },
  { id: 214, value: "ORELLANA" },
  { id: 215, value: "AGUARICO" },
  { id: 216, value: "LA JOYA DE LOS SACHAS" },
  { id: 217, value: "LORETO" },
  { id: 218, value: "SANTO DOMINGO" },
  { id: 219, value: "SANTA ELENA" },
  { id: 220, value: "LA LIBERTAD" },
  { id: 221, value: "SALINAS" },
  { id: 222, value: "LAS GOLONDRINAS" },
  { id: 223, value: "MANGA DEL CURA" },
  { id: 224, value: "EL PIEDRERO" }
];
